### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by Konatus** [mapk/monostack#2]
Hi, i have a fresh new install of wordpress and i just try to display some RSS news and i posted a sample article.
I show u what it's look like : 
![image](https://user-images.githubusercontent.com/25751709/48676614-7281c200-eb69-11e8-8650-e27e9d679ce1.png)
![image](https://user-images.githubusercontent.com/25751709/48676626-a2c96080-eb69-11e8-952b-1e2e2e834237.png)

**Comment by mapk** [comment]
Which version of WordPress are you using? I just tried this with 5.0.3 and it worked fine using the RSS feed from `https://wordpress.org/news/`

**Comment by mapk** [comment]
I haven't heard any response, and since it appears to be working with the latest WP version, I'm closing this issue.
