### ISSUE TITLE
iframe doesnt work

### ISSUE THREAD

**Issue by slayer01** [mapk/monostack#3]
Hey,

it looks like iframes do not work in monostack.
If I hit preview in gutenberg, the iframe is displayed properly but in frontend not.

any Ideas?

**Comment by mapk** [comment]
I just tried adding this in the code editor:

`<p><iframe src="https://markuraine.com" width="100%" height="400px"></iframe></p>`

and it worked great. 

![screen shot 2019-01-23 at 8 21 58 pm](https://user-images.githubusercontent.com/617986/51654400-90461b80-1f4c-11e9-94c7-6a375582c542.png)

Are you using the Gutenberg editor?

**Comment by mapk** [comment]
Haven't heard any response, and as it appears to be working fine, I'm closing this issue.
