### ISSUE TITLE
Syntax highlight isn't working on WP 5.0.2

### ISSUE THREAD

**Issue by altucor** [mapk/monostack#4]
![monostack_not_working](https://user-images.githubusercontent.com/31515257/50532841-19be2580-0b28-11e9-86e7-4304a7e724fc.png)
As you can see syntax highlight not working. Probably because I've made post via graphics mode and wp automatically puts tags (like nbsp, li, p) in my text and after that, js regexp functions cannot extract key words. Also variable "word" contains not a word, it contains whole line. Variable "word" from that file at line 21 https://github.com/mapk/monostack/blob/master/js/syntax-highlighting.js

On that image I've put console.log() at 21 line in to the file above

**Comment by altucor** [comment]
Possible solution from me, but i'm not js developer. 
`line = line.replaceAll("&nbsp;", " &nbsp; ");
line = line.replaceAll("<li>", " <li> ");
line = line.replaceAll("</li>", " </li> ");
line = line.replaceAll("<ol>", " <ol> ");
line = line.replaceAll("</ol>", " </ol> ");
line = line.replaceAll("<p>", " <p> ");
line = line.replaceAll("</p>", " </p> ");

wordsArr = line.split(" ");
outputLine = ""

wordsArr.forEach(function(word){
	if ( prepositions.test( word ) ) {
		outputLine += "<span class=\"highlight-prepositions\">" + word + "</span>";
	} else if ( conjunctions.test( word ) ) {
		outputLine += "<span class=\"highlight-conjunctions\">" + word + "</span>";
	} else if ( pronouns.test( word ) ) {
		outputLine += "<span class=\"highlight-pronouns\">" + word + "</span>";
	} else{
		outputLine += word;
	}
});

return outputLine;`

**Comment by mapk** [comment]
Hmmm. I'm using 5.0.3 right now and syntax highlighting is working great. Have you tried in 5.0.3 yet? It shouldn't matter if you create the content in _visual_ or _code_ editor.

**Comment by mapk** [comment]
I haven't any response, and as it appears to be working for me, I'm closing this issue.
