### ISSUE TITLE
disable syntax highlighting

### ISSUE THREAD

**Issue by micha1987** [mapk/monostack#6]
Hey there. could you tell me where i can disable syntax highlighting in the .css?

**Comment by Narmos** [comment]
Hi, you can comment these lines on wp-content/themes/monostack/style.css :

> .entry-content .highlight-conjunctions {
>   color: var(--color_blue);
> }
> .entry-content .highlight-prepositions { 
>   color: var(--color_pink); 
> } 
> .entry-content .highlight-pronouns { 
>   color: var(--color_green);
> }

or (seems better) just comment this line on wp-content/themes/monostack/js/syntax-highlighting.js :

> wp_enqueue_script( 'monostack-syntax-highlighting', get_template_directory_uri() . '/js/syntax-highlighting.js', array(), '20180816', true );

**Comment by mapk** [comment]
Yes, the latter part of @Narmos' comment is probably best. Just comment out the JS file.

**Comment by RAMOhio** [comment]
I had the same question and didn't want to modify the theme files so I ended up making some changes under *Appearance* > *Customize* > *Additional CSS*

I added this to the additional CSS:
```
.highlight-conjunctions {
    color: inherit!important;
}
.highlight-prepositions {
    color: inherit!important;
}
.highlight-pronouns {
    color: inherit!important;
}
```

I wrote more detail on [my blog](https://codetips.org/2020/12/17/how-do-i-remove-syntax-highlighting-from-the-monostack-wordpress-theme/) but that should be enough info to do this without modifying theme files.

@mapk great work on the theme btw, it's beautiful even without the highlighting! Really wish I could have left the highlighting in but it was really hard to read (for me at least)
