### ISSUE TITLE
excerpt missing

### ISSUE THREAD

**Issue by hozza** [mapk/monostack#7]
Great theme, just one thing missing (maybe an error?) - no post excerpts are shown anywhere?

**Comment by hozza** [comment]
I see you've done this on purpose in 'content.php' for non-single posts (home page) - I agree the whole post should not be shown if the author misses a `<!--more-->` tag but you could use the more on-purpose `<?php the_excerpt(); ?>` which is shown in the new Gutenberg editor, in-case the author explicitly wants an excerpt shown on the home page.

**Comment by mapk** [comment]
Fixed with commit 1f4b1e561e6ce64311ea32dbf4aeee22f7754b59

I'll get a new version up in the theme dir soon.
