### ISSUE TITLE
Page doesn't load correctly with https

### ISSUE THREAD

**Issue by misaalanshori** [mapk/monostack#8]
![image](https://user-images.githubusercontent.com/38964181/55676900-0204f300-5908-11e9-9be8-baefb1078f68.png)
That is how the homepage loads when using https

![image](https://user-images.githubusercontent.com/38964181/55676915-2b258380-5908-11e9-99f0-3a59d6fba0c8.png)
and that's how it looks without https

[apparently](https://stackoverflow.com/questions/15452519/problems-loading-style-sheets-over-https) it's because the link to the css file uses http and not https

I'm not sure how to fix this because i don't know how to modify the theme files.
heres the website https://adminispwd.com

**Comment by mapk** [comment]
I don't think that's the problem. I tested the theme on a couple of different `https` sites and it works fine for me. I've also seen it on other people's `https` sites looking good too. 

There must be another problem. If you still have trouble resolving this, maybe try to contact your hosting provider?
